### ISSUE TITLE
chercher un nombre dans un tableau

### ISSUE THREAD

**Issue by Teva** [VivianePons/courses#1]
Hello,

A moins que le dernier élément du tableau (liste) soit la variable a, le code suivant retournera toujours "False"

```
def find(T,a):
    for b in T:
        if b == a:
            return True
        return False
```

Le suivant fonctionne :

```
def find(T,a):
...     if a in T:
...             return True
...     return False
```

**Comment by VivianePons** [comment]
Are you referring to the code in find.py ?

In this case, the exact code is

```
def find(T, a):
    for b in T:
        if b == a:
            return True
    return False
```

and so the `return False` is outside the `for` block and it works. I know the other way, but I wanted to make the algorithm explicit in the code. If ever you've seen this elsewhere with the error you mention, please tell me where.

**Comment by Teva** [comment]
> and so the return False is outside the for block 

ok my bad
